- Framework/include/BJet.h
- Framework/include/Jet.h
Added variables to Jet.h (including cleaning and JetID)
> Added variables to Jet.h (including cleaning and JetID)

- Framework/include/BJet.h
- Framework/include/Baseline.h
- Framework/include/Jet.h
Compiled and ran locally and everything works. Will show plots next Wednesday (or sooner if people want them), but wanted to make it available in case people wanted to use the new GoodJets collection (have not implement GoodBJets yet)
> Added Jet Cleaning based on Delta R and Pt Matching

- Framework/cfg/sampleCollections_v3.cfg
- Framework/cfg/sampleSets_v3.cfg
Add samples for 2017 ntuples from the V15 ntuple production round. Note that this round doesn't contain a complete set of samples.
> V15 samples

- Framework/include/ScaleFactors.h
> Updating ht scale factor: now cant go negative and not change the total number of events

- Framework/include/ScaleFactors.h
Adds PS weights. Currently includes 2 sets of 4 weights: ISR/FSR Up/Down by factor 2 or sqrt(2).
> PS weights

- Framework/include/ScaleFactors.h
For the record, the electron scale factors were updated, but the muon scale factors have not changed. Please also update your lepton scale factor histograms.
> Updated MiniAODV3 Lepton SFs

- Framework/include/Baseline.h
- Framework/include/Jet.h
- Framework/include/Muon.h
Not fully implemented. I still need to do jet cleaning and implementing the QCD CR switch properly in the calculating of the MVA score.
> Added non iso muon object to framework

- Framework/include/ScaleFactors.h
Added HT scale factor based on Madgraph sample and created corresponding variables (htUp, htDown, totalScaleFactor). 
Also, fixed absolute value of muon bug.
> Added MG based HT scale factor

- Framework/include/Baseline.h
- Framework/include/ScaleFactors.h
- Framework/include/Utility.h
Add a noTrig version of the electron and muon SFs in `ScaleFactors.h`
Add `PassTriggerMuon2018` and `PassTriggerElectron2018` to `Baseline.h`
> Makes Changes for AnalyzeLepTrigger

- Framework/include/Baseline.h
- Framework/include/RunTopTagger.h
(1) RunTopTagger.h:
-- updated the genMatch function
-- added new variables for fake rate study
(2) Baseline.h:
-- defined a new basline for 0 lepton case
> fixed the gen match and added some variables for Fake Rate study for resolved top tagger

- Framework/include/RunTopTagger.h
- Framework/include/ScaleFactors.h
> Now using the new lepton trig. eff SF 

- Framework/include/ScaleFactors.h
No longer using lambda functions
> Getting ready to cacluate the HT scale factor for 2018

- Framework/include/ScaleFactors.h
Added a print statement for getBin errors
> Fixed a lepton scale factor issue for 2018

- Framework/include/MakeMT2Hemispheres.h
- Framework/include/RunTopTagger.h
(1) Before we used MT2 analysis MT2 calculation (Davis method). 
(2) Now, we use CMS MT2 calculation (Lester method)
(3) Added pt and mass rank stop masses
(4) Updated the analyzer for the Njets
> Changed MT2 calculation, add pt & mass rank Stop Masses

- Framework/include/MakeMT2Hemispheres.h
Fixed the registers for stop1ScalarPt_ScalarPtRank and stop2ScalarPt_ScalarPtRank
> fixed the variable registerations

- Framework/include/Jet.h
- Framework/include/SetUpTopTagger.h
- Framework/src/SetUpTopTagger.cc
(1) Updated the Jet.h to add new jets collection called GoodJets_pt20 which are required pt > 20 && eta < 2.4 for the top tagger jet mask 
(2) Updated SetUpTopTagger to filter this GoodJets_pt20 inside AK4 jets collection
> updated the Jet module to mask the AK4 jets

- Framework/include/MakeStopHemispheres.h
- Added if statement that sorts out which seeding method to use for each jet collection when using Hemisphere reconstruction (this resolves warning about the max iteration limit in stop reconstruction)
> Resolved Hemispheres max iterations warning

- Framework/include/Hemispheres.h
- Framework/include/MakeStopHemispheres.h
- Framework/src/Hemispheres.cc
- Used an enum in MakeStopHemispheres.h to clarify which seeding method is used in each module
> Added enum to handle seeding method argument

- Framework/include/CommonVariables.h
- Framework/include/FatJetCombine.h
replacement for alextemp, fatjetcombine.h was overhauled to remove cuts. If used by other selection bjets need to be identified another way
> Fatjetupdate

- Framework/include/CommonVariables.h
- Framework/include/FatJetCombine.h
merging with branch containing NN variables
> including FatJetCombine update

- Framework/include/ISRJets.h
- Framework/scripts/getSamplesCfg.sh
Create a module to the ISR gen matching for identification of the ISR jets
> ISRmatching

- Framework/cfg/sampleSets_v6_2.cfg
QCD, TT, TTJets samples were added for ISR jet study
> ISRsamples

- Framework/include/MakeMVAVariables.h
- Framework/include/MakeStopHemispheres.h
- Framework/scripts/getSamplesCfg.sh
We added the stop 4-vector variables, which are boosted and rotated, for NN
> Added the stop variables for NN

- Framework/include/BJet.h
- Framework/include/Jet.h
- for NN input file maker
- do for NGoodJets and NGoodBjets for different pt cuts
> Add Double Version of Some Counts Variables

- Framework/include/CommonVariables.h
- Framework/include/MakeMVAVariables.h
- Framework/include/PrepNTupleVars.h
--add lepton isolation
--add jet energy fractions
--add jet deep flavour
> Add Some Vars to NN Inputs

- Framework/include/BJet.h
- Framework/include/Baseline.h
- Framework/include/CommonVariables.h
- Framework/include/PrepNTupleVars.h
(1) Added new baselines selections for trigger efficiency and trigger scale factor
(2) Included hadronic triggers 
(3) Included separate muon trigger to used for the pre-selections (to select the Single Muon events)
> updated for trigger efficiency and scale factor study

- Framework/include/MakeMVAVariables.h
get the jet variables with the related good jet collections for 0-lepton and 1-lepton respectively
> debugged for NN input variables

- Framework/include/Baseline.h
- Framework/include/DeepEventShape.h
- Framework/include/MakeMVAVariables.h
- Framework/include/StopGenMatch.h
--remove some unused variables in some places
--when creating the Jets_cm_top6 vector, append the 0l or 1l suffix
--handle the bin edges correctly when defining ABCD bin variables and handle 0l and 1l cases
> Fixup and Cleanup

- Framework/include/Baseline.h
--cleaned up proto 0L baseline that goes into full "good" 0L baseline
> Minor Adjustment to Proto 0L Baseline

- Framework/include/Baseline.h
To avoid improper comparisons and their conclusions
> Always Blind Data and MC Together

- Framework/include/Baseline.h
Changed 0L baseline to have the following requirements:
- ge 1 top
- ge 1 b jet
- ge 7 jets
> 0 lep update

- Framework/include/RunTopTagger.h
**Create new analyzer: **Analyzer/src/TopTagger_Analyzer.cc**:**
- make any top tagger performance plots for Resolved, Merged, Resolved+Merged taggers
- uses the **Framework/include/RunTopTagger.h**
**Note that** **Analyzer/src/AnalyzeTopTagger.cc** is for only Resolved tagger study:
- it is for WP optimization for stop reconstruction
- uses the  **TopTaggerTools/Tools/include/HistoContainer.h**
> added new variables to make fake rate, efficiency and ROC plots

- .gitignore
> Let the Repo See .cfg

- Framework/cfg/sampleSets_UL_v1.cfg
--updated `sampleSets_UL_v1.cfg` now that some data samples ntuple production have been completed.
> Some Updated Event Counts

- Framework/include/MakeMVAVariables.h
> Generalize MakeMVAVariables

- Framework/cfg/sampleCollections_UL_v1.cfg
--make sure all TT variations get added to `2016{pre,post}_AllTT`.
--add `2018pre` and `2018post` versions of `2018` samples.
> Updates to sampleCollections

- Framework/include/CommonVariables.h
- Framework/include/PrepNTupleVars.h
--moved code from `PrepNTupleVars` to `CommonVariables` to have access to veto booleans
--brought event weight calculation with as one self-contained block of code
> Hot Fix for HEM Veto

- Framework/include/CommonVariables.h
- Framework/include/RunTopTagger.h
For the first test of UL samples, Updated the vectors based on TopTaggerTools/Tools/include/HistoContainer.h to run ResolveTopTagger_Analyzer:
1. to get fake rate & efficiency plots
2. to get  ROC plot including all WPs
> updated for using UL and testing first time

- Framework/include/MakeMVAVariables.h
Adding 0l combined 7th jet into framework for NN inputs
> Adding 0l combined 7th jet

- Framework/include/MakeStopHemispheres.h
Make a version of stop pt that is scaled by HT like the other pt variables for use in the NN.
> Add Scaled pt for Stop 4-Vector

- Framework/include/RunTopTagger.h
- Framework/include/StopJets.h
-- Change commented out code in `RunTopTagger.h` to be an if statement based on the name of the config file
-- Consider merged tops in `StopJets.h`
> Fix Some Things in Framework

- Framework/include/CommonVariables.h
- Framework/include/Electron.h
- Framework/include/RunTopTagger.h
- Framework/include/ScaleFactors.h
Revive some old code in `ScaleFactors.h` to register `FinalWeight` taking into account everything we usually do by hand in the analyzers.
Some other minor cleanup as well.
> Register FinalWeight for Any Channel

- Framework/include/CommonVariables.h
- Framework/include/StopGenMatch.h
--do not need to do a GEN match in `CommonVariables`
--no usage of double Mbl
> Cleanup Some Old Code

- Framework/cfg/sampleCollections_UL_v2.cfg
Add `TTTJ` to `2017_TTX_skim` collection
> Do Not Forget TTTJ for 2017 skim

- Framework/include/Baseline.h
- Framework/include/ScaleFactors.h
Fixing bug where non-iso muon trigger had x and y bin definitions flipped
> Changes before Pre-Approval
