StealthStop/Framework

Framework/cfg/sampleSets_v2_skim.cfg
Had to comment out TTTT because there were no output files from the skim and change the naming convention of WJetsToLNu
=> Changes to sampleSet.cfg

Framework/cfg/sampleSets_v6.cfg
After disentangling 2016 and 2016v3, the following samples are "actually" missing:
TT_isrUp
TTZH
tZq_W_lept_Z_hadron
=> WIP: Adjust Event Numbers for Some 2016 Samples

Framework/cfg/sampleSets_v6.cfg
Capitalization in filelist name does not follow friendly name for user.
=> Do not change syntax for filelist

BackgroundMVA/test/Makefile, Framework/include/DeepEventShape.h
Recently, a renaming of the `include` folder in the `TopTagger/CfgParser` module [1] took place. It is now called `interface`. This has been reflected in the relevant places in the `Framework` module.
[1] https://github.com/susy2015/TopTagger/commit/9bd7a884f6cc28c5e385e7e797354b7b68aa2a53
=> Follow upstream change in TopTagger repo: include ==> interface

Framework/include/Jet.h, Framework/include/MakeMVAVariables.h, Framework/include/MakeStopHemispheres.h, Framework/include/StopJets.h, Framework/include/Utility.h, Framework/src/Utility.cc
- Fixed MakeStopHemispheres.h so that it uses the jet collection passed as a parameter in the reconstruction
- Added variable which specifies the seeding method used
- Changed jet mask pt requirement from 45 GeV to 20 GeV
- Removed extra comments in StopJets.h
=> Fixed bug in hemisphere code, cleaned up StopJets

Framework/cfg/sampleCollections_v6.cfg, Framework/cfg/sampleSets_v6.cfg, Framework/include/StopJets.h
* Moved new VLQ samples into the StealthStop EOS area and implemented them into the framework
* Changed the ranking system for the tops in the stop jets collection. The result of this change is the second seed for the hemisphere reconstruction will now be determined by (deltaR of top with first axis)*(pt of top)
=> Added high mass VLQ samples to framework, changed the ranking of tops in the StopJets collection

Framework/include/FatJetCombine.h, Framework/include/MakeMVAVariables.h
-some jet variables do not have a varied version; just use nominal in this case and avoid the suffix.
=> Make Sure MakeNJetDists Works

Framework/include/ISRJets.h, Framework/include/StopJets.h
(1) There has already been ISR jet filter which is below:
** Get the ISR jets by using the truth information of ISR
-- with deltaR cut
-- with deltaR and pT ratio cuts
(2) ISR status code was updated:
** We had used status code 71 before
-- ISR is added by Pythia in the Parton shower level with status codes 41-49, 71-79 in MC
-- But this status code include not only ISR but also FSR and other information
-- So we won't use any status code from Parton shower level
** Updated ISR status code is 23
-- ISR is added by Madgraph or Powheg in the Matrix element level with status code 23 in MC
(3) We added the new filter which is below:
** Get the NonISR jets by using the TreeMaker method
--This method getting the NonISR jets (signal jets), which are coming from our decays
(4) We also added …
=> added a new ISR jet filter

Framework/include/MakeMVAVariables.h
Jets are rotated in phi with respect to leading jet. Using this same angle, also rotate the leptons and MET.
=> Rotate Leptons and MET in Phi

Framework/include/DeepEventShape.h
-register the three outputs for the double disco + mass reg NN: disc1, disc2, and massReg
-use bin edges in NN model .cfg to define and register the ABCD bins in the framework.
=> register double disco outputs, define ABCD bins

Framework/include/MakeMVAVariables.h
- simply boost and rotate the AK8 jets to same frame that the AK4 jets, MET, and leptons are boosted and rotated into.
=> Rotate and Boost AK8 Jets to Same Frame as Other Objects

Framework/include/StopGenMatch.h
--gets GEN-matched stops or tops depending on which MC sample we are running on
--for the moment, neutralino information is discarded, see git history if wanted back
=> Update StopGenMatch to Correctly Get GEN-matched RECO Stops

Framework/include/FatJetCombine.h
There was one place in `FatJetCombine.h` where `TLorentzVector`s could be grabbed from the -1 element of  a vector (if the index in the vector was never determined beyond the initial value of -1). This would sometimes lead to obscure `TVector2` errors about NaNs coming from the `TVector2::Phi_mpi_pi` function. A simple protection is added to prevent this from occurring.
=> Protect Against Sneaky Out-of-Bounds in FatJetCombine

Framework/include/BTagCorrector.h, Framework/include/Baseline.h, Framework/include/EventShapeVariables.h, Framework/include/FatJetCombine.h, Framework/include/ISRJets.h, Framework/include/MakeStopHemispheres.h, Framework/include/MegaJetCombine.h, Framework/include/StopGenMatch.h, Framework/include/StopJets.h
It was brought to my attention while working on #254 that we should go through the different modules and make sure we are using `myVarSuffix_` everywhere it should be. This PR does just that and makes numerous spot fixes.
A notable change is how `MakeStopHemispheres` is instantiated. There is now an additional `label_` member variable that contains the information that _was_ being passed as `myVarSuffix_` i.e. containing "0l" or "1l" in all the output variable names etc. Thus, `myVarSuffix_` can then be used properly as it is used for all the other modules.
I have tested these changes with the `MakeNNVariables` analyzer, which utilizes many of the main modules.
=> Sort Out Abuse/Misuse of myVarSuffix_

Framework/include/DeepEventShape.h
--changes will allow the `DeepEventShape` module to get bin edges / boundaries for all regions defined in a neural network config file.
* a new array called `regions` is intended to be added to the neural network `cfg` file, which lists as simple strings the name of the regions
* an array of edges / boundaries per-Njets is to be provided for each region, where the name of the edges array is `binEdges_NAME`
* the array of simple disc1, disc2 edges per-Njets coming directly from the neural network keep the same array name as before: `binEdges`
* the array of edges for a region is a set of two edges defining the "ABCD" region and then four boundaries that contain the region for each Njets bin.
* These edges / boundaries appear in the order:
```
disc1edge
disc2edge
leftBoundary
rightBoundary …
```
=> Update DeepEventShape to Handle Multiple Regions in NN Cfg

Framework/include/Baseline.h
--when making `TTJets_Incl` for NN inputs, don't veto with mad HT, but only temporary, so undo here.
=> Remove Temporary Comment Out

Framework/include/Baseline.h
I just updated the list of hadronic triggers for each year.
You can see the details: https://indico.cern.ch/event/1029895/#7-semras-progress
**Note that**
1. **2016**: we don't include _**HLT_PFJet500**_  for not overlapping
-- OR'd others based the run ranges
3. **2017**: we don't include _**HLT_PFJet550**_  for not overlapping
-- OR'd others based the run ranges
5. **2018**: we don't include _**HLT_PFJet550**_  for not overlapping
-- OR'd others based the run ranges
For more details, please look at this specific slides: https://indico.cern.ch/event/1029895/contributions/4324312/attachments/2228162/3859841/UL_Hadronic_Trigger_Lists.pdf
=> updated the triggers for 0l channel

Framework/include/Baseline.h
- Adding in runYear "2018" in if statement for checking if an event passes trigger requirements
=> Fix issue when running over 2018 UL ntuples

Framework/include/Electron.h
Year tag for 2018 was still only looking for pre and post. Now will check for "2018" as well
=> Fixing 2018 yearTag Bug in electron cut

Framework/include/Baseline.h
- New selections with more strict Ht requirement. We are hoping that this will reduce the number of QCD events with very high weights that pass our SR selection
=> New selections with increased Ht requirements

Framework/include/Baseline.h
--a handful of trigger names for 0L were missing a `_` after the `HLT`, thus these triggers would never be found in the list or checked properly
=> Fix Some Trigger Names for 0L

Framework/src/Utility.cc
There is a bug in `Framework/src/Utility.cc` concerning the parsing of the trigger paths string [1].
The variable `substr` needs to be pushed back to the vector `vs` rather than `string` itself.
Thus, instead of making a vector of individual trigger path names, the entire concatenated list of trigger path names was being pushed back _n_ times.
The effect of this is that `passTrigger` like bools will always report as true...
[1] https://github.com/StealthStop/Framework/blob/master/Framework/src/Utility.cc#L56-L72
=> Fix String Splitting Utility Function

Framework/include/MakeMVAVariables.h, Framework/include/Utility.h, Framework/src/Utility.cc
For flexibility, template the `DeltaR` and `DeltaPhi` functions in `Utility` so that we do not have to think about if a vector is a `TLorentzVector` or a `LorentzVector`, they both implement, the `Phi` and `Eta` methods.
=> Template the DeltaR and DeltaPhi Functions

Framework/include/ScaleFactors.h
For 2D trigger SF histograms, pt is on the x-axis and eta is on the y-axis (in contrast to similar 2D scale factor histograms produced centrally). This was causing zeroing of the trigger scale factor for muons.
=> Assumed Axes for Trigger SF Histograms

Framework/include/DeepEventShape.h
With the latest training procedure (i.e. for the v2.0-tagged Double DisCo trainings for 0L and 1L), disc1 and disc2 are no longer at the 0th and 2nd index of the length four output vector. They are now at the 0th and 1st index, respectively. Please see @cros0400 for more details.
=> NN Output Locations Change

Framework/include/DeepEventShape.h, Framework/include/JetAK8.h, Framework/include/MakeMVAVariables.h
--give a more clear name to the `FatJetCombine.h` module in that it makes `GoodJetAK8` collections (one collection that is).
--take the opportunity to simplify `MakeMVAVariables.h` to not do anything with AK8 jets, as we do not use them for any channel's double DisCo network.
=> Rename FatJetCombine as JetAK8 and Cleanup

Framework/include/Baseline.h
With latest v2 `sampleSets` and `sampleCollections` (i.e. latest production of V20 ntuples) we now have HT-binned samples for WJets and DYJets that go all the way down to 70 for all years. Thus, simplify the logic for determining the `passMadHT` boolean to reflect this.
=> Handling passMadHT for WJets and DYJets

Framework/include/ScaleFactors.h
Default to 1.0 bTag SF value when running the `CalculateSFMean` analyzer and do not try and get said SF from the tree reader as we do not run `BTagCorrector` when running this SF Mean analyzer.
=> bTag SF Not Needed when Running CalculateSFMean

Framework/include/StopJets.h
--do not rely on constituent index for checking double counting of constituent for merged tops.
--just check if an AK4 jet is within 0.8 of the merged top and if so do not add to list of stop jets to cluster.
=> No Double Counting Merged Top Energy

Framework/include/PrepNTupleVars.h
--total b disc now reads as probb + probbb + problepb
--as it is recommended in e.g. https://twiki.cern.ch/twiki/bin/view/CMS/BtagRecommendation106XUL16preVFP
=> Include lepb Component in Total DeepFlavour b Discriminant

Framework/include/Baseline.h, Framework/include/CommonVariables.h, Framework/include/RunTopTagger.h
--Determine `passMadHT` in `CommonVariables.h` rather than in `Baseline.h`. In this way, some modules (e.g. `Calculate*SF*` analyzers specifically) that need the `passMadHT` boolean do not need to run `Baseline.h` to get it.
--Likewise, because these SF analyzers no longer have to run `Baseline.h`, they also no longer need to run `RunTopTagger` either.
--Therefore, in `Baseline.h` do not try and get `ntops` when running either of these `Calculate*SF*` analyzer modules.
--The definition of `lostCauseEvent` is moved early in the module chain to `CommonVariables.h`. Thus, the definition must be loosened (based simply on Njets, HT, and NBjets) as there is no knowledge of the actual baseline booleans in `CommonVariables.h`.
--However, this early definition, allows `fastMode` to be active for …
=> Module Running Optimization

Framework/include/BTagCorrector.h
To accommodate sample set names with "_skim" in them, the `BTagCorrector` needs to simply chop off the `_skim` suffix when looking for a btag efficiency histogram and use the "nominal" histogram for the given sample.
=> Handle Data Set Names Containing "_skim"

Framework/include/MiniTupleMaker.h, Framework/src/MiniTupleMaker.cc
The names of the trigger paths, whose results are stored in the `vector<int>` `TriggerPass` branch, are put into a concatenated string that is set as the title of the `TriggerPass` branch itself. When running `MiniTupleMaker`, this title is not automatically passed on to the branch in the new TTree. So here we explicitly set that title in an exceptional case. It seems we have to do the title setting *after* we have filled at least once, otherwise we will be trying to set a title with a `void*` pointer...
=> Handle TriggerPass Branch Title

Framework/include/Jet.h, Framework/include/ScaleFactors.h
- Reverting to the NNLO / NLO top pt reweighing scheme
- Adding in pileup ID tight function 
- Noticed that we need to apply different requirements based on year. 2016pre and post are the same, 2017 and 2018 are the same but different from 2016.
=> Tops and PuID

Framework/include/samples.h, Framework/src/samples.cc, Framework/src/samplesModule.cc
Extend the `FileSummary` and `SampleSet` classes to handle a case where four event numbers are parsed. In this case, the first two event numbers are the *generated* positive and negative weighted event counts, while the latter two numbers are the *actual* positive and negative weighted event counts.
The event weight that is calculated inside of `FileSummary` class always uses the *generated* event counts as this corresponds to the absolute total number of events we have to work with for the sample. When running on a skimmed version of a data set, the *actual* positive and negative event counts will differ from their *generated* counter parts. These *actual* event counts correspond to the number of events actually in the skimmed data set.
The *actual* version of the event counts is used …
=> Handle Two Types of Event Counts

Framework/include/BTagCorrector.h, Framework/include/Baseline.h, Framework/include/DeepEventShape.h, Framework/include/MakeMVAVariables.h, Framework/include/MakeStopHemispheres.h, Framework/include/RunTopTagger.h, Framework/include/ScaleFactors.h, Framework/include/StopGenMatch.h, Framework/include/StopJets.h
To avoid any "stale" TChain nonsense when trying to activate and access a TBranch for the first time after having moved the TTree pointer multiple times (corresponding to moving to the next file in the chain), elect to always run the full module path and activate any relevant branches on the first event, regardless of `fastMode`. This preserves the "goodness" of the pointers to the TBranches i.e. no zero values or empty vectors. No obvious solution for `NTupleReader` at this time, which is where something like this should be handled.
=> Guarantee Run of Module Path on First Event

Framework/include/Baseline.h
No longer used by `HadTriggers_Analyzer`. See companion PR: https://github.com/StealthStop/Analyzer/pull/420
=> No Longer Need RefAN Muon Triggers

Framework/include/ScaleFactors.h
We have been calculating a `TotalWeight` inside of `ScaleFactors.h` for convenience of use inside `AnalyzeDoubleDisCo`. This update generalizes and extends the concept to include variations of the weight due to any up/down systematic. This includes scale parameters, PDF, b tag, prefiring, lepton ID+trig, jet trig, and pileup. A companion PR is: https://github.com/StealthStop/Analyzer/pull/422
=> Implement Variations of TotalWeight

Framework/include/ScaleFactors.h
Companion PR: https://github.com/StealthStop/Analyzer/pull/432
Decide to deprecate HT SF related things here (can clean up in `CalculateSFMean` as well).
Simplify getting of histograms since all names are the same for all years.
Miscellaneous other cleanup of some things.
=> Cleanup ScaleFactors

Framework/include/ScaleFactors.h
"Robustify" the `getHisto` function in `ScaleFactors.h` to print out any histogram names that cannot be found in a corresponding scale factor ROOT file.
=> Be More Careful with Histogram Check

Framework/include/Baseline.h, Framework/include/ScaleFactors.h
I updated the Jet, Electron and Muon trigger SFs. because we switched to the DeepFlavor for b-tagging.
**Jet trigger SFs:**
1. I got two histograms for jet SFs: one with exactly 1b, another ≥2b
2. Also, I renamed the histograms
**Electron and Muon SFs**
1. I used the same electron and muon SFs for 1l and 2l channels.
2. Also, I renamed the histograms
=> updating for triggerr scale factors

Framework/include/RunTopTagger.h, Framework/include/ScaleFactors.h
Companion PR: https://github.com/StealthStop/Analyzer/pull/423
This PR adds functionality to `ScaleFactors` to calculate a final top tagger SF in the same we calculate the b tag SF.
Here we use the "method 1a" as used for the b tag SF, which incorporates efficiency and mistag rate.
The `ScaleFactors` module is now passed a top tagger histogram file that contains SF histos as well as overall efficiency and mistag rate histograms.
Attn: @semrat and @cmadrid1, if I understand how the b tag SF works, then we need to discuss how we do the same sort of thing for top tagger i.e. can we cut on the top discriminator _inside our framework_ and then count tops ? Rather than passing the working point to the top tagger module. I would like to discuss further.
=> Support for Top Tagger SF

Framework/include/ScaleFactors.h
When grabbing histograms from SF ROOT files, we need to scrape off the `_skim` suffix at the end of any skim version of a filetag/sample. So do that in `ScaleFactors.h`
=> Handle Skim Filetags Carefully

Framework/include/ScaleFactors.h
Implement up/down variation of event weight for top tagger SF
Implement different versions of QCDCR event weight by varying the different components, btag, pileup, etc.
=> Scale Factor Cleanup Redux 

Framework/include/CommonVariables.h, Framework/include/ScaleFactors.h
`CommonVariables.h` : Default `mll` to `-999.0` so that in cases of same sign or opposite flavor, 2L events will have a more clear nonphysical value. Prevents those events from piling up in the lowest bin of an Mll plot. Only a superficial change for plotting.
`ScaleFactors.h` : Calculate uncertainty on top tagging efficiency/mistag rate a la method used when doing a binomial divide of two histograms (like how we divide histograms for trigger scale factors). The formula is taken directly from the ROOT source. This also prevents the occurrence of `NaN` up and down variations of the top tagger SF when the numerator of the efficiency/mistag rate is 0.
=> Small Updates to Framework

Framework/include/ScaleFactors.h
The `CalculateSFMean` module does not include the `RunTopTagger` module in its module pipeline to run (as it does not need to) and because of this, the top tagger SF calculation in `ScaleFactors.h` is skipped when running `CalculateSFMean`. As an aside, the b tag SF is also not accessed in `ScaleFactors.h` in this scenario too because the `BTag` modules are also excluded from `CalculateSFMean`'s module pipeline (again, it does not need to run them). Note that this "skipping" is necessary to avoid trying to access information that is not present in the tuple reader when the top tagger and b tag modules are not run. In either of these cases, a one-time info message is printed for the user when running the `CalculateSFMean` module.
=> Avoid Calculating Top Tag SF when Running CalculateSFMean Module

Framework/include/ScaleFactors.h
We do not need the b tag SF when computing variations of the event weight used for events in the QCD CR. This is a minor impact as we have yet to look at anything in the CR with these kinds of weight variations.
=> b Tag SF Not Needed for QCDCR Weight Variations

Framework/include/ScaleFactors.h
A long time ago in a galaxy far, far away, we had to handle "reduced" and "default" PSweights simultaneously, as the 2016 ISR and FSR up/down variations were separately generated samples, while 2017 and 2018 simply stored weight variations inside the PSweights vector. Now that all MC samples store the aforementioned variations inside the PSweights, we can, and the recommendation is to use the "default" set always [1]. Somewhere along the way of overhauling our Framework to be UL compliant, we inadvertently defaulted (no pun intended) to using the "reduced" PSweights as the "default". This PR corrects this so that we use the "default" version going forward.
Note that for a human analyzer to pick up these changes one simply can rerun their favorite analyzer. Re-ntuplizing and/or re-skimming …
=> Use Default Rather than Reduced PSweights

Framework/include/BJet.h, Framework/include/CommonVariables.h
Calculate invariant mass between the two b jets (`Mbb`) that are used for computing dR between them. Calculate this `dR_bjets` and `Mbb` using `NonIsoMuonBJets_pt30`, a collection which is produced in `BJet.h`.
Also, use a unique definition of `lostCauseEvent` when running the `MakeQCDValTree` analyzer for producing mini tuples for the QCD Validation study.
=> Variable Support for QCD Validation Studies

Framework/src/MiniTupleMaker.cc
Only try and set branch name of `TriggerPass` branch when the user is actually trying to add it to their mini tuple.
=> Flexible Tupling

Framework/include/MakeMVAVariables.h
In `MakeMVAVariables`, keep track of GoodLepton `iso` and `flav` (i.e. electron or muon) for ease of accessing and then storing in a `TTree` from a `MiniTupleMaker` analyzer later on.
=> Add Lepton Iso and Flav to MakeMVAVariables

Framework/include/CommonVariables.h, Framework/include/RunTopTagger.h
Add separately best top candidate information for resolved tops and merged tops in an event. Also, add `lostCauseEvent` condition for the `MakeTopTagSFTree` mini-tuple producer.
=> Support for MakeTopTagSFTree Analyzer

Framework/include/ScaleFactors.h
Swapped eta and pt binning for non-iso muon trigger scale factors to match the histograms axis definitions
=> Fix binning bug
